### ISSUE TITLE
file_watch raises QueueFull exception on event trigger

### ISSUE THREAD

**Issue by rcarrillocruz** [ansible/event-driven-ansible#130]
I have the following rulebook:

```
- name: Local Test Runner Rules
  hosts: all
  sources:
    - name: file_watch
      ansible.eda.file_watch:
        path: "/home/cloud-user/folder-to-watch"
        recursive: true
  rules:
    - name: run tests 1
      condition: event.type == "DirModifiedEvent"
      action:
        debug:
```

Then, I run it with rulebook with:

```
[cloud-user@ricky-aap-containerized-installer eda]$ ansible-rulebook -i inventory.yml --rulebook rulebook.yml --verbose
2023-05-22 15:57:29,369 - ansible_rulebook.app - INFO - Starting sources
2023-05-22 15:57:29,369 - ansible_rulebook.app - INFO - Starting rules
2023-05-22 15:57:29,369 - ansible_rulebook.engine - INFO - run_ruleset
2023-05-22 15:57:29,370 - drools.ruleset - INFO - Using jar: /home/cloud-user/.local/lib/python3.9/site-packages/drools/jars/drools-ansible-rulebook-integration-runtime-1.0.1-SNAPSHOT.jar
2023-05-22 15:57:29 987 [main] INFO org.drools.ansible.rulebook.integration.api.rulesengine.AbstractRulesEvaluator - Start automatic pseudo clock with a tick every 100 milliseconds
2023-05-22 15:57:29,991 - ansible_rulebook.engine - INFO - ruleset define: {"name": "Local Test Runner Rules", "hosts": ["all"], "sources": [{"EventSource": {"name": "file_watch", "source_name": "ansible.eda.file_watch", "source_args": {"path": "/home/cloud-user/folder-to-watch", "recursive": true}, "source_filters": []}}], "rules": [{"Rule": {"name": "run tests 1", "condition": {"AllCondition": [{"EqualsExpression": {"lhs": {"Event": "type"}, "rhs": {"String": "DirModifiedEvent"}}}]}, "actions": [{"Action": {"action": "debug", "action_args": {}}}], "enabled": true}}]}
2023-05-22 15:57:30,003 - ansible_rulebook.engine - INFO - load source
2023-05-22 15:57:30,615 - ansible_rulebook.engine - INFO - load source filters
2023-05-22 15:57:30,615 - ansible_rulebook.engine - INFO - loading eda.builtin.insert_meta_info
2023-05-22 15:57:31,187 - ansible_rulebook.engine - INFO - Calling main in ansible.eda.file_watch
2023-05-22 15:57:31,190 - ansible_rulebook.engine - INFO - Waiting for all ruleset tasks to end
2023-05-22 15:57:31 190 [drools-async-evaluator-thread] INFO org.drools.ansible.rulebook.integration.api.io.RuleExecutorChannel - Async channel connected
2023-05-22 15:57:31,191 - ansible_rulebook.rule_set_runner - INFO - Waiting for actions on events from Local Test Runner Rules
2023-05-22 15:57:31,192 - ansible_rulebook.rule_set_runner - INFO - Waiting for events, ruleset: Local Test Runner Rules
```

If I run 'touch lol'  at /home/cloud-user/folder-to-watch, then rulebook raises exception:

```
2023-05-22 15:58:16,677 - asyncio - ERROR - Exception in callback FilteredQueue.put_nowait({'change': 'modified', 'meta': {'received_at': '2023-05-22T19:58:16.677597Z', 'source': {'name': 'file_watch', 'type': 'ansible.eda.file_watch'}, 'uuid': '086c6ff7-4d6...-4c36eebafde3'}, 'root_path': '/home/cloud-...lder-to-watch', 'src_path': '/home/cloud-...lder-to-watch', ...})
handle: <Handle FilteredQueue.put_nowait({'change': 'modified', 'meta': {'received_at': '2023-05-22T19:58:16.677597Z', 'source': {'name': 'file_watch', 'type': 'ansible.eda.file_watch'}, 'uuid': '086c6ff7-4d6...-4c36eebafde3'}, 'root_path': '/home/cloud-...lder-to-watch', 'src_path': '/home/cloud-...lder-to-watch', ...})>
Traceback (most recent call last):
  File "/usr/lib64/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/cloud-user/.local/lib/python3.9/site-packages/ansible_rulebook/engine.py", line 82, in put_nowait
    self.queue.put_nowait(data)
  File "/usr/lib64/python3.9/asyncio/queues.py", line 151, in put_nowait
    raise QueueFull
asyncio.queues.QueueFull
```

**Comment by zchef2k** [comment]
I came here for the same error but for a slightly different reason. I realize this is an old issue and you may have moved on, but try setting your condition to one of `created|deleted|modified|moved` [per event source code](https://github.com/ansible/event-driven-ansible/blob/main/extensions/eda/plugins/event_source/file_watch.py#L43).

My action will fire on a condition match and I get an almost identical traceback whenever a file operation in the directory I'm watching _doesn't_ match the condition. Is this expected? It doesn't crash the rulebook but it seems like it should handle this more gracefully.

**Comment by rpelisse** [comment]
@zchef2k I'm running into the same issue:
```
---
- name: Check webserver
  hosts: all
  sources:
        delay: 10
    - ansible.eda.file_watch:
        path: /opt/wildfly/wildfly-33.0.2.Final/standalone/log/server.log 
        recursive: false
  rules:
    - name: Restart Wildfly if OOM is detected
      condition: event.file_watch.status == "modified"
      action:
        run_playbook:
          name: oom.yml
```

I suspect, maybe wrongly, that, because the logfiles gets suddenly filled with a lot of new lines, each one becomes an event and thus fill the queue, but maybe I am wrong? And/or there is a way to change this behavior?

**Comment by zchef2k** [comment]
> @zchef2k I'm running into the same issue:
> 
> ```
> ---
> - name: Check webserver
>   hosts: all
>   sources:
>         delay: 10
>     - ansible.eda.file_watch:
>         path: /opt/wildfly/wildfly-33.0.2.Final/standalone/log/server.log 
>         recursive: false
>   rules:
>     - name: Restart Wildfly if OOM is detected
>       condition: event.file_watch.status == "modified"
>       action:
>         run_playbook:
>           name: oom.yml
> ```
> 
> I suspect, maybe wrongly, that, because the logfiles gets suddenly filled with a lot of new lines, each one becomes an event and thus fill the queue, but maybe I am wrong? And/or there is a way to change this behavior?

Use `event.change` as the left side of your condition.

**Comment by rpelisse** [comment]
Ah,  I know it was about me being stupid :)

So like that:
```
event.file_watch.event.change # match when change is true?
```
Or should I keep the equals to "modified"?

(I try both, and while they suppress the "queue full error", none seems to trigger my oom.yml play...)

**Comment by zchef2k** [comment]
`condition: event.change == "modified"`

**Comment by rpelisse** [comment]
Sorry, I should have indeed check the [source code](https://github.com/ansible/event-driven-ansible/blob/586ea78462ebe506b788224d346011bea3c8f3b6/extensions/eda/plugins/event_source/file_watch.py#L65) before asking the question, my bad.

However, this is not working (as I expect, at least). I am no longer running into the Queue Full, but the addition of text into the logfile being watched does not trigger. Also, if I restart the server (which deletes and recreates the logfile), I run again into the Queue full.

I've tried to workaround this like that: 
```
    - name: Ignore if logfile is created or destroyed
      condition: event.file_watch.event.change == "created" or event.file_watch.event.change == "deleted"
      action:
        run_module:
          name: debug
          module_args:
            msg: "Ignore"

    - name: Restart Wildfly if OOM is detected
      condition: event.file_watch.event.change == "modified"
      action:
        run_playbook:
          name: oom.yml
```
But, the issue happening when the event is added to the queue, it does not work, nor help :(

**Comment by rpelisse** [comment]
@zchef2k 🤦 Thanks! It works now! Changing the logfile does trigger the oom.yml

@Alex-Izquierdo For what it's worth, I've tested your PR and it does fix for me the QueueFull error. :ok_hand:

**Comment by Alex-Izquierdo** [comment]
The fix is merged and it will be available in the next release.
