### ISSUE TITLE
systemd-python not available on pip

### ISSUE THREAD

**Issue by thedoubl3j** [ansible/event-driven-ansible#153]
the systemd-python package is not available via pypi. the package being listed in the requirements.txt causes EE builds to break due to it not being packaged correctly there. It is available via dnf per the packages [documentation](https://github.com/systemd/python-systemd#installation). 

With this package being available in dnf, it will need to be moved to a bindep.txt file for proper consumption by ansible-builder so that it can resolve the dependency correctly. 

```
+ /usr/bin/python3.9 -m pip install --cache-dir=/output/wheels -r /tmp/src/requirements.txt
WARNING: Running pip install with root privileges is generally not a good idea. Try `python3.9 -m pip install --user` instead.
Collecting azure_servicebus
  Downloading azure_servicebus-7.11.1-py3-none-any.whl (390 kB)
Collecting aiobotocore
  Downloading aiobotocore-2.5.2-py3-none-any.whl (72 kB)
Collecting aiohttp
  Downloading aiohttp-3.8.5-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
Collecting aiokafka
  Downloading aiokafka-0.8.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
Collecting watchdog
  Downloading watchdog-3.0.0-py3-none-manylinux2014_x86_64.whl (82 kB)
Collecting systemd_python
  Downloading systemd-python-235.tar.gz (61 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-iv9vdn8z/systemd-python/setup.py'"'"'; __file__='"'"'/tmp/pip-install-iv9vdn8z/systemd-python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-zvaexoht
         cwd: /tmp/pip-install-iv9vdn8z/systemd-python/
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-iv9vdn8z/systemd-python/setup.py", line 55, in <module>
        **lib('libsystemd', 'libsystemd-journal', **defines))
      File "/tmp/pip-install-iv9vdn8z/systemd-python/setup.py", line 40, in lib
        status, result = pkgconfig(name, **kw)
      File "/tmp/pip-install-iv9vdn8z/systemd-python/setup.py", line 18, in pkgconfig
        status, result = call(pkgconf, '--libs', '--cflags', package)
      File "/tmp/pip-install-iv9vdn8z/systemd-python/setup.py", line 6, in call
        cmd = Popen(cmd,
      File "/usr/lib64/python3.9/subprocess.py", line 951, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/lib64/python3.9/subprocess.py", line 1821, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'pkg-config'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Error: building at STEP "RUN /output/scripts/assemble": while running runtime: exit status 1
```

**Comment by konstruktoid** [comment]
Yes it is: https://pypi.org/project/python-systemd/

You're just missing a dependency, eg `sudo apt-get install python3-dev`

**Comment by ssbarnea** [comment]
Closing as https://pypi.org/project/systemd-python is available. At best we can consider the report as incomplete.
